In [1]:
import pandas as pd

try:
    df = pd.read_csv('보행자_사고_다발지역.csv', encoding='utf-8')
except UnicodeDecodeError:
    df = pd.read_csv('보행자_사고_다발지역.csv', encoding='cp949')

df.head()

,사고다발지fid,사고다발지id,법정동코드,지점코드,시도시군구명,지점명,사고건수,사상자수,사망자수,중상자수,경상자수,부상신고자수,경도,위도,다발지역폴리곤
0,6778887,2022040,1111017100,11110001,서울특별시 종로구1,서울특별시 종로구 명륜2가(성균관대입구교차로 부근),9,10,1,9,0,0,126.998780,37.582940,"{""type"":""Polygon"",""coordinates"":[[[126.9996779..."
1,6779548,2022040,1111013700,11110002,서울특별시 종로구2,서울특별시 종로구 낙원동(낙원상가 부근),8,8,0,8,0,0,126.988435,37.571899,"{""type"":""Polygon"",""coordinates"":[[[126.9893336..."
2,6779517,2022040,1111011900,11110003,서울특별시 종로구3,서울특별시 종로구 세종로(세종로180 부근),7,8,0,8,0,0,126.976899,37.569865,"{""type"":""Polygon"",""coordinates"":[[[126.9777971..."
3,6779511,2022040,1111017500,11110004,서울특별시 종로구4,서울특별시 종로구 숭인동(신설동역6번출구 부근),7,8,0,7,1,0,127.023747,37.575111,"{""type"":""Polygon"",""coordinates"":[[[127.0246448..."
4,6779131,2022040,1111013800,11110005,서울특별시 종로구5,서울특별시 종로구 종로2가(종로2가교차로 부근),7,8,0,7,0,1,126.987315,37.570091,"{""type"":""Polygon"",""coordinates"":[[[126.9882136..."

In [2]:
try:
    df = pd.read_csv('서울교통공사_지하철_시각장애인_음성유도기_설치_위치_정보_20260213.csv', encoding='utf-8')
except UnicodeDecodeError:
    df = pd.read_csv('서울교통공사_지하철_시각장애인_음성유도기_설치_위치_정보_20260213.csv', encoding='cp949')

df.head()

   연번  호선  외부역번호       역명                       설치위치
0   1   1    133  서울역 (1)                 4호선 환승통로출구
1   2   1    133  서울역 (1)                   서울역측 개표소
2   3   1    133  서울역 (1)  서울역측 발매기 앞 천장(142번 발매기 위)
3   4   1    133  서울역 (1)          역무실 앞(자동발매기 앞 기둥)
4   5   1    133  서울역 (1)      역무실 앞 중간개표소(내부) B계단 위

In [3]:
import pandas as pd

df = pd.read_csv('서울시_경사도_등고선.csv', encoding='utf-8-sig')
print(df.shape)
df.head()

(13704, 8)

,UFID,DIVI,CONT,SCLS,FMTA,HEIGHT,SHAPE_LEN,geometry
0,1000037709008F00110000000000097632,CTD002,490.0,F0017111,2015001,490.0,753.868258,LINESTRING (217531.16339999996 442031.98540000...
1,1000037709008F00110000000000097633,CTD002,480.0,F0017111,2015001,480.0,3409.613338,LINESTRING (217619.93840000033 442119.01759999...
2,1000037709008F00110000000000097635,CTD002,465.0,F0017111,2015001,465.0,3875.317653,LINESTRING (217619.38879999984 442380.25359999...
3,1000037709008F00110000000000097636,CTD001,475.0,F0017114,2015001,475.0,3571.586296,LINESTRING (217619.9243999999 442125.691600000...
4,1000037709018F00110000000000097643,CTD002,470.0,F0017111,2015001,470.0,4500.693987,LINESTRING (216061.6157999998 439641.166999999...

In [4]:
try:
    df = pd.read_csv('서울시_경사도_표고점.csv', encoding='utf-8')
except UnicodeDecodeError:
    df = pd.read_csv('서울시_경사도_표고점.csv', encoding='cp949')

df.head()

,UFID,NUME,SCLS,FMTA,HEIGHT,geometry
0,1000037612038F00210000000000397699,213.080002,F0027217,2015001,213.080002,POINT (193483.8055999996 434424.1713999994)
1,1000037709034F00210000000000526833,68.430000,F0027217,2015001,68.430000,POINT (207458.63200000022 434498.13859999925)
2,1000037709034F00210000000000526798,150.309998,F0027217,2015001,150.309998,POINT (206892.51640000008 434497.41479999945)
3,1000037612037F00210000000000397890,39.209999,F0027217,2015001,39.209999,POINT (191463.3892000001 434416.9054000005)
4,1000037709032F00210000000000527155,342.640015,F0027217,2015001,342.640015,POINT (203624.76719999965 434482.0854000002)

In [5]:
import pandas as pd

try:
    df = pd.read_csv('서울시_장애인편의시설_목록정보(한국사회보장정보원)_.csv', encoding='utf-8')
except UnicodeDecodeError:
    df = pd.read_csv('서울시_장애인편의시설_목록정보(한국사회보장정보원)_.csv', encoding='cp949')

df.head()

,설립일자,순번,시설위도,시설경도,시설명,시설대표자성명,시설유형,시설기본주소,영업상태구분코드,영업상태구분명,복지로관리시설구분코드,시설ID
0,20120130,20155836847,0.000000,0.000000,서울강동초등학교 다목적강당,NaN,초등학교,서울 강동구 상암로14길 77,Y,영업,17,1174011000-1-03060000
1,20010910,20155836848,37.547399,127.146421,명성교회 월드글로리아센터,NaN,대피소,서울 강동구 양재대로134길 52(명일동),Y,영업,17,1174010100-1-03400001
2,20170425,20155836852,0.000000,0.000000,수유역두산위브아파트1-번1동,NaN,대피소,서울 강북구 덕릉로41길 12,Y,영업,17,KODIX-SL-0000001
3,19980411,20155836853,37.621078,127.028624,풍양조씨풍양군파종회(송중동),NaN,대피소,서울 강북구 도봉로 136 풍양회관,Y,영업,17,KODIX-SL-0000006
4,19980411,20155836854,37.625637,127.026798,삼성생명-미아동,NaN,대피소,서울 강북구 도봉로 188 삼성생명빌딩,Y,영업,17,KODIX-SL-0000056

In [6]:
import pandas as pd

try:
    df = pd.read_csv('음향신호기_현황.csv', encoding='utf-8')
except UnicodeDecodeError:
    df = pd.read_csv('음향신호기_현황.csv', encoding='cp949')

df.head()

,MGRNU,A062_MGRNU,DRN_CDE,ESB_YMD,CAE_YMD,XCE,YCE,MK_CPY,SL_NUM,WORK_CDE,...,SIXID,STAT_CDE,CTK_MGRNU,SD_MGRNU,HISID,POS,FRM_CDE,MNG_AGEN,XGEO,geometry
0,24-0000011058,02-0000180110,0.0,20151026.0,20230102.0,187968.300000,549055.306244,대한신호,NaN,6,...,1264566.0,1.0,2023-0101-005,24-011058,15786,1.0,2.0,NaN,oracle.sql.STRUCT@15216338,POINT (187968.299999927 549055.306243806)
1,24-0000011081,02-0000180117,0.0,20140808.0,20210720.0,186876.700000,551491.393744,대한신호,NaN,6,...,1249343.0,1.0,2021-0101-035,24-011081,15809,1.0,2.0,NaN,oracle.sql.STRUCT@3aa2e0a8,POINT (186876.699999921 551491.393743825)
2,24-0000013895,02-0000178874,180.0,20250409.0,20250409.0,185617.877085,548627.649122,대한신호,NaN,1,...,12138710.0,1.0,2025-0101-051,24-013895,18623,1.0,2.0,NaN,oracle.sql.STRUCT@7fdf03d3,POINT (185617.877084836 548627.649122097)
3,24-0000009872,02-0000178546,180.0,20201102.0,20240621.0,185915.025000,544027.506243,대한신호,NaN,6,...,1124459.0,1.0,2024-0101-092,24-009872,14600,1.0,2.0,NaN,oracle.sql.STRUCT@78b31c60,POINT (185915.024999914 544027.506243215)
4,24-0000009871,02-0000178545,180.0,20201102.0,20240621.0,185899.612500,544026.424993,대한신호,NaN,6,...,1124458.0,1.0,2024-0101-092,24-009871,14599,1.0,2.0,NaN,oracle.sql.STRUCT@661588ed,POINT (185899.612499911 544026.424993082)